version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_lar10
    ports:
      - "8080:80"
    volumes:
      - ../learn_lar10:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel10

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_lar10
    volumes:
      - ../learn_lar10:/var/www
    ports:
      - "9000:9000"
      - "9003:9003"
    environment:
      PHP_IDE_CONFIG: "serverName=laravel10"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel10

  mysql:
    image: mysql:8.0
    container_name: mysql_lar10
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel10
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel10

networks:
  laravel10:
    driver: bridge 